- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution != 'Ubuntu'

- include_tasks: setup-Ubuntu.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution == 'Ubuntu'

- name: Add {{ ansible_user }} to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  register: docker_user_added

- name: Restart to let {{ ansible_user }} get its new group activated.
  when: docker_user_added is changed
  reboot:
