- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: "present"

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- debug: var=ansible_distribution_release
- debug: var=ansible_distribution
- debug: var=ansible_architecture
- debug: var=ansible_lsb.id

- name: Add Docker repository (Raspberry PI 32-bit)
  when: ansible_architecture == "armv7l" and ansible_lsb.id == "Raspbian"
  shell: echo "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_distribution_release|lower }} stable" > /etc/apt/sources.list.d/docker.list

- name: Add Docker repository (Raspberry PI 64-bit)
  when: ansible_architecture == "aarch64" and ansible_lsb.id == "Raspbian"
  shell: echo "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_distribution_release|lower }} stable" > /etc/apt/sources.list.d/docker.list

- name: Add Docker repository (amd64).
  when: ansible_architecture == "x86_64" and not ansible_lsb.id == "Raspbian"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present
    update_cache: true

- name: Block aufs-dkms
  shell: "apt-mark hold aufs-dkms"
  when:
    - ansible_lsb.id == "Raspbian"

- name: Install docker (Raspberry PI)
  when: ansible_lsb.id == "Raspbian"
  apt:
    update_cache: yes
    install_recommends: no
    name:
      - "docker-ce=5:19.03.6~3-0~raspbian-buster"
    state: "present"

- name: Install docker (amd64)
  when: not ansible_lsb.id == "Raspbian"
  apt:
    update_cache: yes
    name:
      - "docker-ce=18.06.3~ce~3-0~debian"
      - "containerd.io"
    state: "present"

- name: Make /etc/docker directory
  file:
    path: /etc/docker
    state: directory

- name: Copy over the daemon configuration
  template:
    src: ./templates/daemon.json
    dest: /etc/docker/daemon.json
  register: deamon_configured

- debug: var=deamon_configured

- name: Restart docker
  when: deamon_configured.changed
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Make /etc/systemd/system/docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
