- name: install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: "present"

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- debug: var=ansible_distribution_release
- debug: var=ansible_distribution
- debug: var=ansible_architecture
- debug: var=ansible_lsb.id

- name: Add Docker repository (ARM 32-bit)
  when: ansible_architecture == "armv7l"
  apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present
    update_cache: true

- name: Add Docker repository (ARM 64-bit)
  when: ansible_architecture == "aarch64"
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present
    update_cache: true

- name: Add Docker repository (AMD64)
  when: ansible_architecture == "x86_64"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present
    update_cache: true

- name: Install docker
  apt:
    update_cache: yes
    name:
      - "docker-ce=5:19.03.6~3-0~ubuntu-bionic"
      - "docker-ce-cli=5:19.03.6~3-0~ubuntu-bionic"
      - "containerd.io=1.2.10-3"
    state: "present"

- name: Make /etc/docker directory
  file:
    path: /etc/docker
    state: directory

- name: Copy over the daemon configuration
  template:
    src: ./templates/daemon.json
    dest: /etc/docker/daemon.json
  register: deamon_configured

- debug: var=deamon_configured

- name: Restart docker
  when: deamon_configured.changed
  service:
    name: docker
    state: restarted
    enabled: yes

- name: Make /etc/systemd/system/docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
