- debug:
    var: ansible_os_family
- name: Distribution
  debug:
    msg: ansible_distribution
- name: Distribution version
  debug:
    msg: ansible_distribution_version
- name: Distribution major version
  debug:
    msg: ansible_distribution_major_version

- name: Check debug
  ansible.builtin.pause:
    prompt: |
      Check status.
      
      ----------------------------
      - Press return to continue -
      ----------------------------

- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution != 'Ubuntu'

- include_tasks: setup-Ubuntu.yml
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution == 'Ubuntu'

- name: Add {{ ansible_user }} to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
#  register: docker_user_added
  notify: Reboot

#- name: Restart to let {{ ansible_user }} get its new group activated.
#  when: docker_user_added is changed
#  reboot:
