- hosts: "{{ hosts | default('all') }}"
  any_errors_fatal: true
  remote_user: pi
  become: true
  gather_facts: no
  roles:
    - role: 0-prereqs
      vars:
        # created with:
        # openssl passwd -salt SomeSalt -1 password
        password: $1$SomeSalt$/jbIwfYCu0MxPBND2EtRH.
