- name: gather facts
  hosts: all
  any_errors_fatal: true
  gather_facts: no

- name: validate the DNS settings
  import_playbook: validate_dns.yml

- name: setup raspberry pis
  import_playbook: setup_rpi.yml
  when: inventory_hostname in groups['rpis']

- name: deploy kubernetes prerequisites
  import_playbook: deploy-1-prek8s.yml

- name: deploy loadbalancer
  import_playbook: deploy-lbs.yml
  when: inventory_hostname in groups['infras']

- name: deploy the masters
  import_playbook: deploy-2-master.yml
  when:
    - inventory_hostname in groups['masters']

- name: deploy nodes
  import_playbook: deploy-3-nodes.yml
  when:
    - inventory_hostname in groups['nodes']

- name: switch to using localhost
  hosts: localhost
- name: deploy applications using argo-cd
  import_playbook: deploy-4-post-kubernetes.yml

