- hosts: all
  any_errors_fatal: true
  gather_facts: no

- import_playbook: validate_dns.yml

- import_playbook: deploy-1-prek8s.yml
  vars:
    hosts: all
    container_environment: "{{ container_env | default('docker') }}"

- import_playbook: setup_rpi.yml


- import_playbook: deploy-lbs.yml
  when: inventory_hostname in groups['infras']

- import_playbook: deploy-2-master.yml
  when:
    - inventory_hostname in groups['masters']
  vars:
    token: abcdef.0123456789abcdef


- import_playbook: deploy-3-nodes.yml
  when:
    - inventory_hostname in groups['workers']
  vars:
    token: abcdef.0123456789abcdef


- hosts: masters[0]
- import_playbook: deploy-4-post-kubernetes.yml
