- name: Install the prerequisites
  hosts: "{{ hosts | default('all') }}"
  any_errors_fatal: true
  become: true
  gather_facts: yes
  roles:
    - role: pre-k8s
      when: inventory_hostname not in groups['infras']
