- name: Apply argocd helm installation.
  kubernetes.core.helm:
    kubeconfig: "{{ k8s_files_kubeconfig }}"
    release_namespace: "{{ argocd_namespace }}"
    create_namespace: true
    chart_ref: argocd
    name: argocd
