- name: Helm - Check if namespace {{ namespace }} exist
  command: "kubectl get ns {{ namespace }}"
  ignore_errors: yes
  register: namespace_check

#- debug:
#    var: namespace_check

- name: Helm {{ namespace }} - Create namespace
  command: "kubectl create ns {{ namespace }}"
  when: namespace_check.rc != 0
