- name: Gathering facts
  setup:

- name: Create k8s argocd namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

- name: Install argocd.
  include_tasks: argocd-install.yml
  when: argocd

- name: Inject startup-secrete for sealed secrets
  include_tasks: sealed-secrets.yaml

- name: Configure argocd app-of-apps.
  include_tasks: argocd-applications.yml
  when: argocd
