- name: Build path to file
  set_fact:
    sealed_secrets_secret: "{{ playbook_dir }}/sealed-secrets-secret.yml"

- name: Check if "{{ sealed_secrets_secret }}" exists
  stat:
    path: "{{ sealed_secrets_secret }}"
  register: secret

- name: Create file if needed
  when: secret.stat.exists
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_files_kubeconfig }}"
    src: "{{ sealed_secrets_secret }}"
