---
- name: Build path to file
  ansible.builtin.set_fact:
    sealed_secrets_secret: "{{ playbook_dir }}/sealed-secrets-secret.yml"

- name: "Check if file exists: {{ sealed_secrets_secret }}"
  ansible.builtin.stat:
    path: "{{ sealed_secrets_secret }}"
  register: secret

- name: Create file if needed
  when: secret.stat.exists
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_files_kubeconfig }}"
    src: "{{ sealed_secrets_secret }}"
