---
# Note that the Apt signing key is supposed to be constant over versions, so the version
# in the URL can safely be ignored.
- name: Add an Apt signing key for Kubernetes repo, uses whichever key is at the URL
  retries: 5
  delay: 5
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_minor_version }}/deb/Release.key"
    state: present

# Very often the adding of repo below fails when updating the cache.
# Best would be to reboot and retry when problem occurs but that seems
# unnecessary hard. References:
# https://dev.to/nodeselector/retrying-groups-of-tightly-coupled-tasks-in-ansible-579d
# https://github.com/ansible/ansible/pull/62151
# When running with "update_cache: no" and letting apt update cache below instead, at least
# the error messages are better and retries works...
- name: Add repo for Kubernetes
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_minor_version }}/deb /
    state: present
    update_cache: false

- name: Install kubeadm and kubelet with version {{ kubernetes_version + '-*' }}
  retries: 6
  delay: 10
  when: kubernetes_version is defined
  ansible.builtin.apt:
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kubeadm={{ kubernetes_version + '-*' }}
      - kubelet={{ kubernetes_version + '-*' }}

- name: Install kubeadm and kubelet with latest version
  retries: 6
  delay: 10
  when: kubernetes_version is not defined
  ansible.builtin.apt:
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - kubeadm
      - kubelet

- name: Enable IP forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: "net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward=1"
    state: present
  notify: Reboot
