- name: Make sure all pods that are supposed to be running, are running
  shell:
    cmd: |
      kubectl -n kube-system get pod -o json |
      jq -r '[.items[] | select(.status.phase != "Running")] | length'
  register: result
  until: result.stdout_lines[0]|int == 0
  retries: 120
  delay: 10
