- name: Install network utility netcat
  become: yes
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - netcat

- name: CentOS - Stop kubelet
  become: yes
  systemd:
    name: kubelet
    daemon_reload: yes
    state: stopped
    enabled: yes

- name: CentOS - Stop docker
  become: yes
  systemd:
    name: docker
    daemon_reload: yes
    state: stopped
    enabled: yes

- name: CentOS - Flush iptables
  become: true
  shell: |
    iptables --flush && \
    iptables -tnat --flush

- name: CentOS - Start docker
  become: yes
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes

- name: CentOS - Start kubelet
  become: yes
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes

- name: CentOS - Wait five seconds before checking for everything is up
  pause:
    seconds: 5

- name: CentOS - Wait for everything to start up
  shell: "nc -z localhost 6443"
  register: connection
  ignore_errors: yes

- debug:
    var: connection

- name: CentOS - Wait for everything to start up
  shell: "nc -z localhost 6443"
  ignore_errors: yes
  register: connection
  until: connection.rc == 0
  retries: 12
  delay: 10
