- name: secondary-master - Reset Kubernetes component
  become: true
  shell: |
    kubeadm reset \
      --force
  register: reset_cluster

- name: secondary-master - Flush iptables
  become: true
  shell: |
    iptables --flush && \
    iptables -tnat --flush

#- debug:
#    var: hostvars[groups['masters'][0]]['certificate_key'][0]

# Certificate key is created by creating the first master
- name: secondary-master - Join master to Kubernetes cluster
  become: true
  when: reset_cluster is succeeded
  shell: |
    kubeadm join \
      --discovery-token {{ token }} \
      --discovery-token-unsafe-skip-ca-verification \
      --control-plane \
      --certificate-key {{ hostvars[groups['masters'][0]]['certificate_key'][0] }} \
      --v=5 \
      --ignore-preflight-errors="{{ ignore_pre_flight_errors }}" \
      {{ kube_api_endpoint }}:6443
  register: init_cluster
  until: "init_cluster.rc == 0"
  retries: 60
  delay: 10

- debug:
    var: init_cluster

# Wait until the API of the master is up.
- include_tasks: probes-api.yaml

- name: secondary-master - Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
  register: started_kubelet
