- name: master - Check swap is disabled
  fail: msg="Swap has to be disabled"
  when: ansible_swaptotal_mb > 0

- name: master - Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- include_tasks: clean.yaml
  when: kubeadm_ca.stat.exists

- name: master - Will be installing this kubernetes version
  debug:
    msg: "{{ kubernetes_version | default('stable-1') }}"

- name: master - Pull the Kubernetes images
  become: yes
  shell: |
    kubeadm config images pull \
      --kubernetes-version {{ kubernetes_version }} \
      {{ init_opts }}
  vars:
    init_opts: ""

- name: master - Init first master of cluster
  include_tasks: "first-master.yml"
  when: inventory_hostname == groups['masters'][0]
  vars:
    - kubeadmin_config: /etc/kubernetes/admin.conf

- debug:
    var: groups['masters'][0]

- fail:
    msg: Debug

- name: master - Join other masters to cluster
  include_tasks: "join.yml"
  when: not kubeadm_ca.stat.exists and not inventory_hostname == groups['masters'][0]

- name: master - Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  become: yes
  register: started_kubelet

- name: master - do facts module to get latest information
  setup:
