- name: master - Check swap is disabled
  fail: msg="Swap has to be disabled"
  when: ansible_swaptotal_mb > 0

- include_tasks: "weave.yml"

- name: master - Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: master - Will be installing this kubernetes version
  debug:
    msg: "{{ kubernetes_version | default('stable-1') }}"

- name: master - Pull the Kubernetes images
  become: yes
  shell: |
    kubeadm config images pull \
      --kubernetes-version {{ kube_version }} \
      {{ init_opts }}
  vars:
    kube_version: "{{ kubernetes_version | default('stable-1') }}"
    init_opts: ""


- debug: var=groups['masters'][0]


- name: master - Init cluster if needed
  include_tasks: "first-master.yml"
  when: not kubeadm_ca.stat.exists and inventory_hostname == groups['masters'][0]
  run_once: yes
  vars:
    - kubeadmin_config: /etc/kubernetes/admin.conf
    - enable_dashboard: true



- name: master - Join new masters if needed
  include_tasks: "join.yml"
  when: not kubeadm_ca.stat.exists and not inventory_hostname == groups['masters'][0]


- name: master - Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  become: yes
  register: started_kubelet


- name: master - do facts module to get latest information
  setup:
