- name: master-weave - Download the weave script
  become: yes
  get_url:
    url: https://git.io/weave
    dest: /usr/local/bin/weave

- name: master-weave - Set execute
  become: yes
  file:
    path: /usr/local/bin/weave
    mode: +x

#- name: master-weave - Use ip-tables in compatible mode
#  become: yes
#  shell: update-alternatives --set iptables "/usr/sbin/iptables-nft"
#  when:
#    - ansible_lsb.id == "Raspbian"
