- name: Update-ca-certs
  become: true
  ansible.builtin.command:
    cmd:
      update-ca-certificates
  changed_when: true

- name: Restart-crio
  become: true
  ansible.builtin.service:
    name: crio
    state: restarted
