- name: Check if {{ cmdline }} exists
  stat:
    path: "{{ cmdline }}"
  register: cmdlinetxt

- name: Create file if needed
  when: not cmdlinetxt.stat.exists
  fail:
    msg: "There is no {{ cmdline }} file."

- name: Test for entry in cmdline.txt
  command: 'grep "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1" {{ cmdline }}'
  register: test_grep1
  ignore_errors: yes

- name: cmdline add
  lineinfile:
    path: "{{ cmdline }}"
    backrefs: True
    state: present
    regexp: '(.*)$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1'
  when: test_grep1.stdout == ""
  register: task_result

- name: Reboot immediately if there was a change in cmdline.txt
  reboot:
  when: task_result is changed
