- name: Wait 300 seconds for target connection to become reachable/usable
  wait_for_connection:
    delay: 0
    timeout: 300

- name: Gathering facts
  setup:

- include_tasks: "swap.yml"

- include_tasks: "expand-file-system.yml"

- include_tasks: "cmdline.yml"
  vars:
    - cmdline: "/boot/cmdline.txt"
  when: ansible_distribution != "Ubuntu"

# Ubuntu is a special case which has their cmdline.txt in different places,
# depending on if BT is enabled or not
- include_tasks: "cmdline.yml"
  vars:
    - cmdline: "/boot/firmware/nobtcmd.txt"
  when: ansible_distribution == "Ubuntu"

- include_tasks: "cmdline.yml"
  vars:
    - cmdline: "/boot/firmware/btcmd.txt"
  when: ansible_distribution == "Ubuntu"

# There is beta support for updating the kernel on Raspberry to 64-bit
- name: Upgrade to 64-bit kernel on Raspberry Buster
  include_tasks: "64bit-pi.yml"
  when:
    - use_64bit is defined
    - ansible_distribution_release == "buster"
    - ansible_architecture == "armv7l"
    - ansible_lsb.id == "Raspbian"
    - ansible_userspace_bits == "32"

- include_tasks: "ssh.yml"

- name: Set password
  user:
    name: "{{ ansible_user }}"
    password: "{{ password }}"

- include_tasks: "hostnames.yml"

- include_tasks: "locale.yml"

- include_tasks: "wireless.yml"
  when:
    - ansible_lsb.id == "Raspbian"
    # This really should be if there is a wireless network

- include_tasks: "apt.yml"

- include_tasks: "ntp.yml"

- name: do facts module to get latest information
  setup:
