---
argo-cd:
  controller:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
  dex:
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
    initImage:
      resources:
        limits:
          memory: 144Mi
        requests:
          cpu: 5m
          memory: 96Mi
  redis:
    resources:
     limits:
       memory: 64Mi
     requests:
       cpu: 10m
       memory: 32Mi
    metrics:
      resources:
        limits:
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
  server:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    extensions:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 64Mi
  repoServer:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  applicationSet:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  notifications:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
