---
- name: Configure UFW to allow access access to local services
  community.general.ufw:
    rule: allow
    port: "'{{ item }}'"
    proto: tcp
  loop:
    - 80  # k8s apps
    - 443  # k8s apps
    - 1936  # HAProxy status
    - 6443  # k8s api
