- ansible.builtin.debug: var=ansible_distribution_release
- ansible.builtin.debug: var=ansible_distribution_major_version
- ansible.builtin.debug: var=ansible_distribution
- ansible.builtin.debug: var=ansible_architecture
- ansible.builtin.debug: var=ansible_lsb.id

- name: Cri-o - Retrive cri-o version from kubernetes version
  ansible.builtin.set_fact:
    CRIO_KUBE_VERSION: "{{ kubernetes_version | regex_search('^[0-9]+\\.[0-9]+') }}"

- name: Cri-o - Set version
  ansible.builtin.set_fact:
    CRIO_VERSION: "{{ CRIO_KUBE_VERSION }}"
  when: not CRIO_KUBE_VERSION == ""

- name: Cri-o - Check that cri-o version could be retrieved from kubernetes_version
  ansible.builtin.fail:
    msg: "Warning: Expected extracted version from '{{ kubernetes_version }}' not to be empty."
  when: CRIO_KUBE_VERSION == ""
  ignore_errors: True

- ansible.builtin.debug:
    msg: "Will use cri-o version {{ CRIO_VERSION }}"

- ansible.builtin.pause:
    seconds: 3600
  when: CRIO_KUBE_VERSION == ""

- name: Cri-o - cri-install-crio - Install CRI-O on Debian
  when: ansible_distribution == "Debian"
  ansible.builtin.include_tasks: install_debian.yaml

- ansible.builtin.fail:
    msg: Cri-o - Unsupported OS
  when: ansible_distribution != "Debian"

- name: Cri-o - Copy registries configuration
  ansible.builtin.template:
    dest: /etc/containers/registries.conf
    src: templates/registries.conf

- name: Cri-o - Install trusted certificates
  ansible.builtin.template:
    src: templates/registry-certificate.crt
    dest: "/usr/local/share/ca-certificates/{{ item.host }}.crt"
  with_items: "{{ trusted_registry_cas }}"
  notify:
    - Update-ca-certs
    - Restart-crio

- name: Cri-o - Make sure cri-o service unit is running
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: crio
