- debug: var=ansible_distribution_release
- debug: var=ansible_distribution_major_version
- debug: var=ansible_distribution
- debug: var=ansible_architecture
- debug: var=ansible_lsb.id


- name: cri-install-crio - Install CRI-O on Debian
  when: ansible_distribution == "Debian"
  include_tasks: install_debian.yaml

- fail:
    msg: cri-install-crio - Unsupported OS
  when: ansible_distribution != "Debian"

- name: cri-install-crio - Copy registries configuration
  template:
    dest: /etc/containers/registries.conf
    src: templates/registries.conf

- name: cri-install-crio - Make sure cri-o service unit is running
  ansible.builtin.systemd:
    enabled: true
    state: started
    name: crio
