apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: example-rule
spec:
  groups:
    - name: example-group
      rules:
        - alert: example-alert
          annotations:
            description: Memory on node {{ $labels.instance }} currently at {{ value }}%
            summary: Memory usage is under pressure, system may become unstable.
          expr: |
            100 - ((node_memory_MemAvailable_bytes{job="node-exporter"} * 100) / node_memory_MemTotal_bytes{job="node-exporter"}) > 70
          for: 2m
          labels:
            severity: warning
