- name: node - Reset Kubernetes component
  become: true
  ansible.builtin.shell: "kubeadm reset --force"
  register: reset_cluster

- name: node - Flush iptables
  become: true
  ansible.builtin.shell: |
    iptables --flush && \
    iptables -tnat --flush
  when: not kubeadm_ca.stat.exists

- name: node - Join Kubernetes cluster
  become: true
  when: reset_cluster is succeeded
  ansible.builtin.shell: |
    kubeadm join \
      --discovery-token {{ token }} \
      --discovery-token-unsafe-skip-ca-verification \
      --ignore-preflight-errors="{{ ignore_pre_flight_errors }}" \
      {{ kube_api_endpoint }}:6443
  register: init_cluster

- name: Enable and check kubelet service
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
  register: started_kubelet

