- name: Reset Kubernetes component
  become: yes
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Init Kubernetes cluster
  become: yes
  when: reset_cluster is succeeded
  shell: |
    kubeadm join \
      --discovery-token {{ token }} \
      --discovery-token-unsafe-skip-ca-verification \
      {{ groups['masters'][0] }}:6443
  register: init_cluster

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  become: yes
  register: started_kubelet

