- name: node - Check swap is disabled
  fail: msg="Swap has to be disabled"
  when: ansible_swaptotal_mb > 0

- name: node - Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

# Clean nodes.
- name: node - Clean out previous kubernetes installation.
  include_tasks: clean.yaml
  when: kubeadm_ca.stat.exists

- name: node - Pull the Kubernetes images
  become: true
  shell: |
    kubeadm config images pull \
      --kubernetes-version {{ kubernetes_version }} \
      {{ init_opts }}
  vars:
    init_opts: ""

- name: node - Join nodes to cluster
  include_tasks: "join.yml"

- name: node - Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
  register: started_kubelet

- name: node - do facts module to get latest information
  setup: {}

- name: node - Approve node certificates
  delegate_to: localhost
  shell:
    cmd: |
      kubectl --kubeconfig {{ k8s_files_kubeconfig }} \
        get csr \
        -o json |\
      jq -r '.items[] | select (.status.conditions == null) | .metadata.name'  |\
      xargs kubectl --kubeconfig {{ k8s_files_kubeconfig }} \
        certificate approve

- name: node - Wait for node to be ready
  delegate_to: localhost
  shell:
    cmd: |
      kubectl get node {{ item }} -o json |\
        jq -r '.status.conditions[] | select(.type == "Ready") | .status'
  register: node_status
  until: node_status.stdout_lines[0] == "True"
  with_items: "{{ groups['nodes'] }}"
  delay: 5
  retries: 12

- name: node - Wait for the rest of the CSRs
  pause:
    seconds: 15

- name: node - Approve node certificates
  delegate_to: localhost
  shell:
    cmd: |
      kubectl --kubeconfig {{ k8s_files_kubeconfig }} \
        get csr \
        -o json |\
      jq -r '.items[] | select (.status.conditions == null) | .metadata.name'  |\
      xargs kubectl --kubeconfig {{ k8s_files_kubeconfig }} \
        certificate approve
