- name: node - Check swap is disabled
  fail: msg="Swap has to be disabled"
  when: ansible_swaptotal_mb > 0

- name: node - Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

# Clean nodes.
- name: node - Clean out previous kubernetes installation.
  include_tasks: clean.yaml
  when: kubeadm_ca.stat.exists

- name: node - Pull the Kubernetes images
  become: true
  shell: |
    kubeadm config images pull \
      --kubernetes-version {{ kubernetes_version }} \
      {{ init_opts }}
  vars:
    init_opts: ""

- name: node - Join nodes to cluster
  include_tasks: "join.yml"

- name: node - Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
  register: started_kubelet

- name: node - do facts module to get latest information
  setup: {}
