- name: "Check if file exists: {{ cmdline }}"
  ansible.builtin.stat:
    path: "{{ cmdline }}"
  register: cmdlinetxt

- name: Create file if needed
  when: not cmdlinetxt.stat.exists
  ansible.builtin.fail:
    msg: "There is no {{ cmdline }} file."
  tags:
    - skip_ansible_lint

- name: Check for entries in cmdline.txt
  ansible.builtin.include_tasks: cmdline-part.yml
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_enable=memory"
    - "cgroup_enable=hugetlb"
    - "cgroup_memory=1"
    - "swapaccount=1"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
