- name: Set the hostname
  ansible.builtin.hostname: name={{ inventory_hostname }}
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: task_result
  notify: Reboot

- ansible.builtin.debug: var=task_result

- ansible.builtin.debug:
    msg: "{{ lookup('community.general.dig', inventory_hostname) }}	{{ inventory_hostname }}"

- name: Build /etc/hosts localhost
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1.*{{ item }}$"
    line: "{{ lookup('community.general.dig', item) }}	{{ item }}"
    state: present
  with_items:
    - "{{ inventory_hostname }}"

- name: Build /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: "^.*{{ item }}$"
    line: "{{ hostvars[item].ansible_host }}	{{ item }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"
