- name: Set the hostname
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: task_result
  notify: Reboot

- debug: var=task_result

- name: build /etc/hosts localhost
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1.*{{ item }}$"
    line: "127.0.0.1	{{ item }}"
    state: present
  with_items:
    - "{{ inventory_hostname }}"

- name: build /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^.*{{ item }}$"
    line: "{{ hostvars[item].ansible_host }}	{{ item }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"
