- name: Keyboard
  replace:
    destfile: /etc/default/keyboard
    regexp: '"gb"'
    replace: '"sv"'
  ignore_errors: yes

- name: Ensure a locale exists
  community.general.locale_gen:
    name: en_GB.UTF-8
    state: present

- name: Set locale
  command: 'update-locale LANG=en_GB.UTF-8'
  register: locale
