- name: set timezone to Central Europe
  community.general.timezone:
    name: Europe/Stockholm

- name: Install ntp
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ntp
      - ntpdate

- name: Copy over the NTP configuration
  template: src=./templates/ntp.conf dest=/etc/ntp.conf
  register: ntp_status

- name: Make ntp directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - /etc/ntp/crypto/pw
    - /etc/ntp/keys


- name: Make sure NTP is stopped
  service:
    name: ntp
    state: stopped
    enabled: yes
  when: ntp_status.changed


- name: Sync time initialy
  shell: ntpd -gq
  when: ntp_status.changed


- name: Make sure NTP is started up
  service:
    name: ntp
    state: started
    enabled: yes
