- name: Set timezone to Central Europe
  community.general.timezone:
    name: Europe/Stockholm

- name: Install ntp
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ntp
      - ntpdate

- name: Copy over the NTP configuration
  ansible.builtin.template:
    src: templates/ntp.conf
    dest: /etc/ntp.conf
    mode: '644'
  register: ntp_status

- name: Make ntp directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '700'
  with_items:
    - /etc/ntp/crypto/pw
    - /etc/ntp/keys

- name: Make sure NTP is stopped
  ansible.builtin.service:
    name: ntp
    state: stopped
    enabled: yes
  when: ntp_status.changed


- name: Sync time initialy
  ansible.builtin.command: ntpd -gq
  when: ntp_status.changed
  changed_when: false


- name: Make sure NTP is started up
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: yes
