# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: Disable swap for now
  command: "{{  item }}"
  when: ansible_swaptotal_mb > 0
  with_items:
    - swapoff --all
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - update-rc.d dphys-swapfile remove
    - systemctl disable dphys-swapfile

- name: Disable swap forever on non-RPI Debian
  command: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  when: ansible_swaptotal_mb > 0

- name: Reboot to apply changes
  reboot:
  when: ansible_swaptotal_mb > 0

- name: Gathering facts
  setup:

- name: Make sure swap is disabled
  fail:
    msg: "Failed to disable swap"
  when: ansible_swaptotal_mb > 0
