# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: Disable swap for now
  ansible.builtin.command: "{{ item }}"
  when: ansible_swaptotal_mb > 0
  with_items:
    - swapoff --all
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - update-rc.d dphys-swapfile remove
    - systemctl disable dphys-swapfile
  changed_when: true

- name: Disable swap forever on non-RPI Debian
  ansible.builtin.command: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  when: ansible_swaptotal_mb > 0
  changed_when: true

- name: Reboot to apply changes
  ansible.builtin.reboot:
  when: ansible_swaptotal_mb > 0

- name: Gathering facts
  ansible.builtin.setup:

- name: Make sure swap is disabled
  ansible.builtin.fail:
    msg: "Failed to disable swap"
  when: ansible_swaptotal_mb > 0
