# Set the wireless regulatory area
- name: crda
  ansible.builtin.replace:
    destfile: /etc/default/crda
    regexp: 'REGDOMAIN='
    replace: 'REGDOMAIN=SE'
  ignore_errors: yes

- name: regdomain
  ansible.builtin.replace:
    destfile: /lib/crda/setregdomain
    regexp: 'REGDOMAIN='
    replace: 'REGDOMAIN=SE'
  ignore_errors: yes

