---
name: CI
"on":
  pull_request:
  push:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'  # caching pip dependencies

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          make dependencies

      - name: Lint code
        run: |
          make lint
